// Code generated by protoc-gen-go.
// source: timberslide.proto
// DO NOT EDIT!

/*
Package ts is a generated protocol buffer package.

It is generated from these files:
	timberslide.proto

It has these top-level messages:
	Event
	EventReply
	Topic
	Register
	RegisterReply
	TopicsReq
	TopicsReply
	TopicMetadata
	UpdateReply
*/
package ts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Topic   string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	Done    bool   `protobuf:"varint,3,opt,name=Done" json:"Done,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventReply struct {
}

func (m *EventReply) Reset()                    { *m = EventReply{} }
func (m *EventReply) String() string            { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()               {}
func (*EventReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Topic struct {
	ID       int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Position int64  `protobuf:"varint,3,opt,name=Position" json:"Position,omitempty"`
	Public   bool   `protobuf:"varint,4,opt,name=Public" json:"Public,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Register struct {
	Topic string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	User  string `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
}

func (m *Register) Reset()                    { *m = Register{} }
func (m *Register) String() string            { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()               {}
func (*Register) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RegisterReply struct {
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type TopicsReq struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
}

func (m *TopicsReq) Reset()                    { *m = TopicsReq{} }
func (m *TopicsReq) String() string            { return proto.CompactTextString(m) }
func (*TopicsReq) ProtoMessage()               {}
func (*TopicsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type TopicsReply struct {
	Topics []*Topic `protobuf:"bytes,1,rep,name=topics" json:"topics,omitempty"`
}

func (m *TopicsReply) Reset()                    { *m = TopicsReply{} }
func (m *TopicsReply) String() string            { return proto.CompactTextString(m) }
func (*TopicsReply) ProtoMessage()               {}
func (*TopicsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TopicsReply) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type TopicMetadata struct {
	Name   string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Public bool   `protobuf:"varint,2,opt,name=public" json:"public,omitempty"`
}

func (m *TopicMetadata) Reset()                    { *m = TopicMetadata{} }
func (m *TopicMetadata) String() string            { return proto.CompactTextString(m) }
func (*TopicMetadata) ProtoMessage()               {}
func (*TopicMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type UpdateReply struct {
}

func (m *UpdateReply) Reset()                    { *m = UpdateReply{} }
func (m *UpdateReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateReply) ProtoMessage()               {}
func (*UpdateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Event)(nil), "ts.Event")
	proto.RegisterType((*EventReply)(nil), "ts.EventReply")
	proto.RegisterType((*Topic)(nil), "ts.Topic")
	proto.RegisterType((*Register)(nil), "ts.Register")
	proto.RegisterType((*RegisterReply)(nil), "ts.RegisterReply")
	proto.RegisterType((*TopicsReq)(nil), "ts.TopicsReq")
	proto.RegisterType((*TopicsReply)(nil), "ts.TopicsReply")
	proto.RegisterType((*TopicMetadata)(nil), "ts.TopicMetadata")
	proto.RegisterType((*UpdateReply)(nil), "ts.UpdateReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ingest service

type IngestClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (Ingest_StreamEventsClient, error)
}

type ingestClient struct {
	cc *grpc.ClientConn
}

func NewIngestClient(cc *grpc.ClientConn) IngestClient {
	return &ingestClient{cc}
}

func (c *ingestClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (Ingest_StreamEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ingest_serviceDesc.Streams[0], c.cc, "/ts.Ingest/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &ingestStreamEventsClient{stream}
	return x, nil
}

type Ingest_StreamEventsClient interface {
	Send(*Event) error
	Recv() (*EventReply, error)
	grpc.ClientStream
}

type ingestStreamEventsClient struct {
	grpc.ClientStream
}

func (x *ingestStreamEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ingestStreamEventsClient) Recv() (*EventReply, error) {
	m := new(EventReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ingest service

type IngestServer interface {
	StreamEvents(Ingest_StreamEventsServer) error
}

func RegisterIngestServer(s *grpc.Server, srv IngestServer) {
	s.RegisterService(&_Ingest_serviceDesc, srv)
}

func _Ingest_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServer).StreamEvents(&ingestStreamEventsServer{stream})
}

type Ingest_StreamEventsServer interface {
	Send(*EventReply) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type ingestStreamEventsServer struct {
	grpc.ServerStream
}

func (x *ingestStreamEventsServer) Send(m *EventReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ingestStreamEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ingest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ts.Ingest",
	HandlerType: (*IngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Ingest_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "timberslide.proto",
}

// Client API for Streamer service

type StreamerClient interface {
	GetStream(ctx context.Context, in *Topic, opts ...grpc.CallOption) (Streamer_GetStreamClient, error)
}

type streamerClient struct {
	cc *grpc.ClientConn
}

func NewStreamerClient(cc *grpc.ClientConn) StreamerClient {
	return &streamerClient{cc}
}

func (c *streamerClient) GetStream(ctx context.Context, in *Topic, opts ...grpc.CallOption) (Streamer_GetStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Streamer_serviceDesc.Streams[0], c.cc, "/ts.Streamer/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamerGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streamer_GetStreamClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type streamerGetStreamClient struct {
	grpc.ClientStream
}

func (x *streamerGetStreamClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Streamer service

type StreamerServer interface {
	GetStream(*Topic, Streamer_GetStreamServer) error
}

func RegisterStreamerServer(s *grpc.Server, srv StreamerServer) {
	s.RegisterService(&_Streamer_serviceDesc, srv)
}

func _Streamer_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamerServer).GetStream(m, &streamerGetStreamServer{stream})
}

type Streamer_GetStreamServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type streamerGetStreamServer struct {
	grpc.ServerStream
}

func (x *streamerGetStreamServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _Streamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ts.Streamer",
	HandlerType: (*StreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _Streamer_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "timberslide.proto",
}

// Client API for Topics service

type TopicsClient interface {
	RegisterTopic(ctx context.Context, in *Register, opts ...grpc.CallOption) (*RegisterReply, error)
	GetTopics(ctx context.Context, in *TopicsReq, opts ...grpc.CallOption) (*TopicsReply, error)
	UpdateTopic(ctx context.Context, in *TopicMetadata, opts ...grpc.CallOption) (*UpdateReply, error)
}

type topicsClient struct {
	cc *grpc.ClientConn
}

func NewTopicsClient(cc *grpc.ClientConn) TopicsClient {
	return &topicsClient{cc}
}

func (c *topicsClient) RegisterTopic(ctx context.Context, in *Register, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/ts.Topics/registerTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicsClient) GetTopics(ctx context.Context, in *TopicsReq, opts ...grpc.CallOption) (*TopicsReply, error) {
	out := new(TopicsReply)
	err := grpc.Invoke(ctx, "/ts.Topics/getTopics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicsClient) UpdateTopic(ctx context.Context, in *TopicMetadata, opts ...grpc.CallOption) (*UpdateReply, error) {
	out := new(UpdateReply)
	err := grpc.Invoke(ctx, "/ts.Topics/updateTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Topics service

type TopicsServer interface {
	RegisterTopic(context.Context, *Register) (*RegisterReply, error)
	GetTopics(context.Context, *TopicsReq) (*TopicsReply, error)
	UpdateTopic(context.Context, *TopicMetadata) (*UpdateReply, error)
}

func RegisterTopicsServer(s *grpc.Server, srv TopicsServer) {
	s.RegisterService(&_Topics_serviceDesc, srv)
}

func _Topics_RegisterTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Register)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicsServer).RegisterTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ts.Topics/RegisterTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicsServer).RegisterTopic(ctx, req.(*Register))
	}
	return interceptor(ctx, in, info, handler)
}

func _Topics_GetTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicsServer).GetTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ts.Topics/GetTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicsServer).GetTopics(ctx, req.(*TopicsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Topics_UpdateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicsServer).UpdateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ts.Topics/UpdateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicsServer).UpdateTopic(ctx, req.(*TopicMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

var _Topics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ts.Topics",
	HandlerType: (*TopicsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerTopic",
			Handler:    _Topics_RegisterTopic_Handler,
		},
		{
			MethodName: "getTopics",
			Handler:    _Topics_GetTopics_Handler,
		},
		{
			MethodName: "updateTopic",
			Handler:    _Topics_UpdateTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timberslide.proto",
}

func init() { proto.RegisterFile("timberslide.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0xf5, 0x82, 0x43, 0x61, 0x30, 0x89, 0x3c, 0xaa, 0x22, 0xc4, 0xc9, 0x5d, 0xa9, 0x2a, 0x97,
	0xba, 0x2e, 0xe9, 0xa5, 0xea, 0xd5, 0x55, 0x65, 0x55, 0xa9, 0xa2, 0x6d, 0x73, 0xae, 0x70, 0x3c,
	0x42, 0x48, 0x18, 0x28, 0xbb, 0xa9, 0x94, 0xbf, 0xe9, 0xa7, 0x56, 0xcc, 0x02, 0xe1, 0x92, 0xdb,
	0xbc, 0xe5, 0xcd, 0x7b, 0xf3, 0x9e, 0x80, 0xb5, 0x29, 0xcf, 0x47, 0xea, 0x74, 0x55, 0x9e, 0x68,
	0xdb, 0x76, 0x8d, 0x69, 0xd0, 0x31, 0x5a, 0x7e, 0x87, 0x8b, 0xaf, 0x7f, 0xa9, 0x36, 0xf8, 0x1a,
	0x2e, 0x7e, 0x35, 0x6d, 0xf9, 0x10, 0x8b, 0x8d, 0x48, 0x03, 0x65, 0x01, 0xc6, 0xf0, 0xea, 0x96,
	0xb4, 0xce, 0x0b, 0x8a, 0x1d, 0x7e, 0x1f, 0x21, 0x22, 0x2c, 0xf7, 0x4d, 0x4d, 0xb1, 0xbb, 0x11,
	0xa9, 0xaf, 0x78, 0x96, 0x2b, 0x00, 0x16, 0x53, 0xd4, 0x56, 0x4f, 0xf2, 0xf7, 0xa0, 0x88, 0x97,
	0xe0, 0x1c, 0xf6, 0xac, 0xeb, 0x2a, 0xe7, 0xb0, 0xef, 0x57, 0x7f, 0xe4, 0xe7, 0x51, 0x91, 0x67,
	0x4c, 0xc0, 0xbf, 0x6b, 0x74, 0x69, 0xca, 0xa6, 0x66, 0x49, 0x57, 0x4d, 0x18, 0xaf, 0xc1, 0xbb,
	0x7b, 0x3c, 0x56, 0xe5, 0x43, 0xbc, 0x64, 0xb3, 0x01, 0xc9, 0x4f, 0xe0, 0x2b, 0x2a, 0x4a, 0x6d,
	0xa8, 0x7b, 0xe1, 0x7c, 0x84, 0xe5, 0xbd, 0xa6, 0x6e, 0x74, 0xea, 0x67, 0x79, 0x05, 0xd1, 0xb8,
	0x65, 0xef, 0x7c, 0x07, 0x01, 0xb3, 0xb5, 0xa2, 0x3f, 0xfd, 0x1d, 0x3d, 0xab, 0xee, 0xef, 0xb3,
	0x52, 0x13, 0x96, 0x3b, 0x08, 0x47, 0x62, 0x5b, 0x3d, 0xe1, 0x1b, 0xf0, 0x0c, 0xc3, 0x58, 0x6c,
	0xdc, 0x34, 0xcc, 0x82, 0xad, 0xd1, 0x5b, 0x26, 0xa8, 0xe1, 0x83, 0xfc, 0x02, 0x11, 0x3f, 0xdc,
	0x92, 0xc9, 0x4f, 0xb9, 0xc9, 0xa7, 0xe8, 0x62, 0x16, 0xfd, 0x1a, 0xbc, 0xd6, 0xc6, 0x73, 0x6c,
	0x3c, 0x8b, 0x64, 0x04, 0xe1, 0x7d, 0x7b, 0xca, 0x0d, 0xb1, 0x5d, 0xf6, 0x19, 0xbc, 0x43, 0x5d,
	0x90, 0x36, 0xf8, 0x01, 0x56, 0x3f, 0x4d, 0x47, 0xf9, 0x99, 0xcb, 0xd6, 0xc8, 0xc6, 0x3c, 0x27,
	0x97, 0xd3, 0x68, 0xb3, 0x2d, 0x52, 0xb1, 0x13, 0xd9, 0x47, 0xf0, 0xed, 0x02, 0x75, 0xf8, 0x16,
	0x82, 0x6f, 0x64, 0x2c, 0xc4, 0xe7, 0x93, 0x93, 0x67, 0x11, 0xb9, 0xd8, 0x89, 0xec, 0x9f, 0x00,
	0xcf, 0x86, 0xc5, 0x0c, 0xa2, 0x6e, 0x28, 0xcc, 0xb6, 0xba, 0xea, 0xa9, 0x63, 0x87, 0xc9, 0x7a,
	0x8e, 0x06, 0x57, 0x7c, 0x0f, 0x41, 0x41, 0x66, 0x10, 0x88, 0x26, 0x97, 0xbe, 0xe2, 0xe4, 0x6a,
	0x0e, 0x2d, 0xfd, 0x06, 0xc2, 0x47, 0x8e, 0x6a, 0x0d, 0xd6, 0x13, 0x63, 0x2c, 0xce, 0x2e, 0xcd,
	0xea, 0x90, 0x8b, 0xa3, 0xc7, 0x7f, 0xf1, 0xcd, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0xae,
	0x47, 0x1d, 0xda, 0x02, 0x00, 0x00,
}
