// Code generated by protoc-gen-go.
// source: gw.proto
// DO NOT EDIT!

/*
Package ts is a generated protocol buffer package.

It is generated from these files:
	gw.proto

It has these top-level messages:
	Event
	EventReply
	Topic
*/
package ts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Topic   string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	Done    bool   `protobuf:"varint,3,opt,name=Done" json:"Done,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventReply struct {
}

func (m *EventReply) Reset()                    { *m = EventReply{} }
func (m *EventReply) String() string            { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()               {}
func (*EventReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Topic struct {
	Topic string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Event)(nil), "ts.Event")
	proto.RegisterType((*EventReply)(nil), "ts.EventReply")
	proto.RegisterType((*Topic)(nil), "ts.Topic")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Ingest service

type IngestClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (Ingest_StreamEventsClient, error)
}

type ingestClient struct {
	cc *grpc.ClientConn
}

func NewIngestClient(cc *grpc.ClientConn) IngestClient {
	return &ingestClient{cc}
}

func (c *ingestClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (Ingest_StreamEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ingest_serviceDesc.Streams[0], c.cc, "/ts.Ingest/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &ingestStreamEventsClient{stream}
	return x, nil
}

type Ingest_StreamEventsClient interface {
	Send(*Event) error
	Recv() (*EventReply, error)
	grpc.ClientStream
}

type ingestStreamEventsClient struct {
	grpc.ClientStream
}

func (x *ingestStreamEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ingestStreamEventsClient) Recv() (*EventReply, error) {
	m := new(EventReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ingest service

type IngestServer interface {
	StreamEvents(Ingest_StreamEventsServer) error
}

func RegisterIngestServer(s *grpc.Server, srv IngestServer) {
	s.RegisterService(&_Ingest_serviceDesc, srv)
}

func _Ingest_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServer).StreamEvents(&ingestStreamEventsServer{stream})
}

type Ingest_StreamEventsServer interface {
	Send(*EventReply) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type ingestStreamEventsServer struct {
	grpc.ServerStream
}

func (x *ingestStreamEventsServer) Send(m *EventReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ingestStreamEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ingest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ts.Ingest",
	HandlerType: (*IngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Ingest_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

// Client API for Streamer service

type StreamerClient interface {
	GetStream(ctx context.Context, in *Topic, opts ...grpc.CallOption) (Streamer_GetStreamClient, error)
}

type streamerClient struct {
	cc *grpc.ClientConn
}

func NewStreamerClient(cc *grpc.ClientConn) StreamerClient {
	return &streamerClient{cc}
}

func (c *streamerClient) GetStream(ctx context.Context, in *Topic, opts ...grpc.CallOption) (Streamer_GetStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Streamer_serviceDesc.Streams[0], c.cc, "/ts.Streamer/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamerGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streamer_GetStreamClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type streamerGetStreamClient struct {
	grpc.ClientStream
}

func (x *streamerGetStreamClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Streamer service

type StreamerServer interface {
	GetStream(*Topic, Streamer_GetStreamServer) error
}

func RegisterStreamerServer(s *grpc.Server, srv StreamerServer) {
	s.RegisterService(&_Streamer_serviceDesc, srv)
}

func _Streamer_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamerServer).GetStream(m, &streamerGetStreamServer{stream})
}

type Streamer_GetStreamServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type streamerGetStreamServer struct {
	grpc.ServerStream
}

func (x *streamerGetStreamServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _Streamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ts.Streamer",
	HandlerType: (*StreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _Streamer_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("gw.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x2f, 0xd7, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x29, 0x56, 0xf2, 0xe6, 0x62, 0x75, 0x2d, 0x4b, 0xcd,
	0x2b, 0x11, 0x12, 0xe1, 0x62, 0x0d, 0xc9, 0x2f, 0xc8, 0x4c, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0x70, 0x84, 0x24, 0xb8, 0xd8, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98,
	0xc0, 0xe2, 0x30, 0xae, 0x90, 0x10, 0x17, 0x8b, 0x4b, 0x7e, 0x5e, 0xaa, 0x04, 0x33, 0x50, 0x98,
	0x23, 0x08, 0xcc, 0x56, 0xe2, 0xe1, 0xe2, 0x02, 0x1b, 0x16, 0x94, 0x5a, 0x90, 0x53, 0xa9, 0x24,
	0x0b, 0x35, 0x11, 0xbb, 0xd1, 0x46, 0x96, 0x5c, 0x6c, 0x9e, 0x79, 0xe9, 0xa9, 0xc5, 0x25, 0x42,
	0xfa, 0x5c, 0x3c, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0x60, 0xcd, 0xc5, 0x42, 0x9c, 0x7a, 0x25,
	0xc5, 0x7a, 0x60, 0xb6, 0x14, 0x1f, 0x9c, 0x09, 0x31, 0x93, 0x41, 0x83, 0xd1, 0x80, 0xd1, 0xc8,
	0x90, 0x8b, 0x03, 0xa2, 0x21, 0xb5, 0x48, 0x48, 0x95, 0x8b, 0xd3, 0x3d, 0xb5, 0x04, 0xc2, 0x85,
	0xe8, 0x04, 0x1b, 0x2f, 0x85, 0x30, 0x44, 0x89, 0xc1, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x65, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x77, 0x21, 0xe8, 0xfe, 0x00, 0x00, 0x00,
}
